from __future__ import annotations

from .models import FlowDefinition


OPERATOR_HAPPY_PATH_STEPS = [
    {
        "step_key": "import_ogv_demand",
        "label": "Import OGV demand",
        "expected_route": "/schedule/ogv-demand",
        "expected_action_id": "IMPORT_OGV_DEMAND",
        "completion_selector": "demand_imported",
        "blocked_selector": "none",
        "required_permission": "schedule.edit",
        "terminal": False,
    },
    {
        "step_key": "review_coal_sequence",
        "label": "Review coal grade sequence",
        "expected_route": "/schedule/coal-grade-sequence",
        "expected_action_id": "REVIEW_COAL_SEQUENCE",
        "completion_selector": "cargo_sequence_clear",
        "blocked_selector": "cargo_sequence_blocked",
        "required_permission": "schedule.view",
        "terminal": False,
    },
    {
        "step_key": "enter_operating_windows",
        "label": "Enter tide and bridge windows",
        "expected_route": "/constraints/tide-bridge",
        "expected_action_id": "ENTER_OPERATING_WINDOWS",
        "completion_selector": "operating_windows_entered",
        "blocked_selector": "none",
        "required_permission": "schedule.edit",
        "terminal": False,
    },
    {
        "step_key": "generate_plan",
        "label": "Generate plan",
        "expected_route": "/operations/tug-barge-assignment",
        "expected_action_id": "GENERATE_PLAN",
        "completion_selector": "plan_generated",
        "blocked_selector": "none",
        "required_permission": "schedule.edit",
        "terminal": False,
    },
    {
        "step_key": "submit_approval",
        "label": "Submit approval",
        "expected_route": "/schedule/published-plan",
        "expected_action_id": "SUBMIT_APPROVAL",
        "completion_selector": "approval_submitted",
        "blocked_selector": "blocking_conflicts_present",
        "required_permission": "schedule.edit",
        "terminal": False,
    },
    {
        "step_key": "approve_plan",
        "label": "Approve plan",
        "expected_route": "/approvals/publishing",
        "expected_action_id": "APPROVE_PLAN",
        "completion_selector": "approvals_complete",
        "blocked_selector": "approval_missing",
        "required_permission": "schedule.approve",
        "terminal": False,
    },
    {
        "step_key": "publish_plan",
        "label": "Publish plan",
        "expected_route": "/approvals/publishing",
        "expected_action_id": "PUBLISH_PLAN",
        "completion_selector": "plan_published",
        "blocked_selector": "approval_missing",
        "required_permission": "schedule.publish",
        "terminal": False,
    },
    {
        "step_key": "generate_export",
        "label": "Generate governed export",
        "expected_route": "/admin/export-handoff",
        "expected_action_id": "GENERATE_EXPORT",
        "completion_selector": "export_generated",
        "blocked_selector": "none",
        "required_permission": "export.generate",
        "terminal": True,
    },
]


PHASE5_PLUS_RECOVERY_STEPS = [
    {
        "step_key": "open_exception_center",
        "label": "Open Exception Center",
        "expected_route": "/exceptions/center",
        "expected_action_id": "OPEN_EXCEPTION_CENTER",
        "completion_selector": "active_disruption_exists",
        "blocked_selector": "none",
        "required_permission": "schedule.view",
        "terminal": False,
    },
    {
        "step_key": "generate_recovery_options",
        "label": "Generate recovery options",
        "expected_route": "/exceptions/center",
        "expected_action_id": "GENERATE_RECOVERY_OPTIONS",
        "completion_selector": "recovery_snapshot_and_run_exists",
        "blocked_selector": "no_active_disruption",
        "required_permission": "schedule.edit",
        "terminal": False,
    },
    {
        "step_key": "review_recommendations",
        "label": "Review recommendations",
        "expected_route": "/recovery/recommendations",
        "expected_action_id": "OPEN_RECOMMENDATION_CONSOLE",
        "completion_selector": "recommendations_exist",
        "blocked_selector": "recovery_run_missing",
        "required_permission": "schedule.view",
        "terminal": False,
    },
    {
        "step_key": "validate_root_cause",
        "label": "Validate root-cause repair",
        "expected_route": "/recovery/recommendations",
        "expected_action_id": "VALIDATE_ROOT_CAUSE_REPAIR",
        "completion_selector": "root_cause_assessment_exists",
        "blocked_selector": "none",
        "required_permission": "schedule.view",
        "terminal": False,
    },
    {
        "step_key": "materialize_recommendation",
        "label": "Materialize recommendation",
        "expected_route": "/recovery/recommendations",
        "expected_action_id": "MATERIALIZE_RECOVERY_RECOMMENDATION",
        "completion_selector": "recommendation_materialized",
        "blocked_selector": "recommendations_missing",
        "required_permission": "schedule.edit",
        "terminal": False,
    },
    {
        "step_key": "run_simulation",
        "label": "Run simulation",
        "expected_route": "/simulation/workspace",
        "expected_action_id": "RUN_SIMULATION",
        "completion_selector": "scenario_run_succeeded",
        "blocked_selector": "scenario_missing",
        "required_permission": "schedule.edit",
        "terminal": False,
    },
    {
        "step_key": "promote_scenario",
        "label": "Promote scenario",
        "expected_route": "/simulation/workspace",
        "expected_action_id": "PROMOTE_SCENARIO",
        "completion_selector": "scenario_promoted",
        "blocked_selector": "scenario_run_missing",
        "required_permission": "schedule.edit",
        "terminal": False,
    },
    {
        "step_key": "repair_remaining_conflicts",
        "label": "Repair remaining conflicts",
        "expected_route": "/exceptions/center",
        "expected_action_id": "REPAIR_PLAN_CONFLICTS",
        "completion_selector": "blocking_conflicts_clear",
        "blocked_selector": "blocking_conflicts_present",
        "required_permission": "schedule.edit",
        "terminal": False,
    },
    {
        "step_key": "run_publishability_check",
        "label": "Run publishability check",
        "expected_route": "/approvals/publishing",
        "expected_action_id": "RUN_PUBLISHABILITY_CHECK",
        "completion_selector": "future_publishability_assessment",
        "blocked_selector": "future_publishability_assessment",
        "required_permission": "schedule.view",
        "terminal": False,
    },
    {
        "step_key": "submit_approval",
        "label": "Submit approval",
        "expected_route": "/schedule/published-plan",
        "expected_action_id": "SUBMIT_APPROVAL",
        "completion_selector": "approval_submitted",
        "blocked_selector": "blocking_conflicts_present",
        "required_permission": "schedule.edit",
        "terminal": False,
    },
    {
        "step_key": "approve_plan",
        "label": "Approve plan",
        "expected_route": "/approvals/publishing",
        "expected_action_id": "APPROVE_PLAN",
        "completion_selector": "approvals_complete",
        "blocked_selector": "approval_missing",
        "required_permission": "schedule.approve",
        "terminal": False,
    },
    {
        "step_key": "publish_plan",
        "label": "Publish plan",
        "expected_route": "/approvals/publishing",
        "expected_action_id": "PUBLISH_PLAN",
        "completion_selector": "plan_published",
        "blocked_selector": "approval_missing",
        "required_permission": "schedule.publish",
        "terminal": True,
    },
]


CANONICAL_FLOW_DEFINITIONS = [
    {
        "flow_key": "operator_happy_path_v1",
        "name": "Operator happy path",
        "description": "UI-driven planning flow from OGV demand import through manual publish.",
        "version": 1,
        "status": FlowDefinition.Status.ACTIVE,
        "entry_route": "/schedule/ogv-demand",
        "steps": OPERATOR_HAPPY_PATH_STEPS,
    },
    {
        "flow_key": "phase5_plus_recovery_v1",
        "name": "Phase 5+ recovery path",
        "description": "Governed recovery flow from exception triage through manual publish.",
        "version": 1,
        "status": FlowDefinition.Status.ACTIVE,
        "entry_route": "/exceptions/center",
        "steps": PHASE5_PLUS_RECOVERY_STEPS,
    },
]


def seed_canonical_flow_definitions() -> list[FlowDefinition]:
    definitions = []
    for spec in CANONICAL_FLOW_DEFINITIONS:
        definition, _ = FlowDefinition.objects.update_or_create(
            flow_key=spec["flow_key"],
            defaults=spec,
        )
        definitions.append(definition)
    return definitions
