# Generated by Django 5.2.14 on 2026-05-17 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetrySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('source_type', models.CharField(choices=[('synthetic_gps', 'Synthetic GPS'), ('synthetic_ais', 'Synthetic AIS'), ('vendor_api', 'Vendor API'), ('manual', 'Manual'), ('device_gateway', 'Device gateway')], max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('degraded', 'Degraded'), ('paused', 'Paused'), ('retired', 'Retired')], default='active', max_length=32)),
                ('freshness_threshold_seconds', models.PositiveIntegerField(default=900)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['source_id'],
                'indexes': [models.Index(fields=['source_type', 'status'], name='telemetry_t_source__3ee295_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssetIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('tug', 'Tug'), ('barge', 'Barge'), ('cts', 'CTS'), ('ogv', 'OGV'), ('service_boat', 'Service boat')], max_length=32)),
                ('asset_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('asset_code', models.CharField(max_length=80)),
                ('external_id', models.CharField(max_length=120)),
                ('external_id_type', models.CharField(choices=[('mmsi', 'MMSI'), ('imo', 'IMO'), ('tracker_id', 'Tracker ID'), ('device_serial', 'Device serial'), ('synthetic_id', 'Synthetic ID')], max_length=32)),
                ('is_primary', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_identities', to='telemetry.telemetrysource')),
            ],
            options={
                'ordering': ['asset_type', 'asset_code', 'source__source_id', 'external_id'],
            },
        ),
        migrations.CreateModel(
            name='PositionPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ping_id', models.CharField(max_length=96, unique=True)),
                ('asset_type', models.CharField(choices=[('tug', 'Tug'), ('barge', 'Barge'), ('cts', 'CTS'), ('ogv', 'OGV'), ('service_boat', 'Service boat')], max_length=32)),
                ('asset_code', models.CharField(max_length=80)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('speed_knots', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('course_degrees', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('heading_degrees', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('device_timestamp', models.DateTimeField()),
                ('received_timestamp', models.DateTimeField()),
                ('signal_quality', models.CharField(choices=[('good', 'Good'), ('weak', 'Weak'), ('stale', 'Stale'), ('invalid', 'Invalid')], default='good', max_length=32)),
                ('accuracy_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('battery_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('raw_payload_ref', models.CharField(blank=True, max_length=255)),
                ('is_synthetic', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset_identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position_pings', to='telemetry.assetidentity')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position_pings', to='telemetry.telemetrysource')),
            ],
            options={
                'ordering': ['-device_timestamp', '-id'],
                'indexes': [models.Index(fields=['asset_code', 'device_timestamp'], name='telemetry_p_asset_c_2703b6_idx'), models.Index(fields=['source', 'received_timestamp'], name='telemetry_p_source__c40cfc_idx'), models.Index(fields=['asset_type', 'asset_code', 'device_timestamp'], name='telemetry_p_asset_t_0c47cf_idx'), models.Index(fields=['is_synthetic', 'device_timestamp'], name='telemetry_p_is_synt_cca89f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='assetidentity',
            index=models.Index(fields=['asset_type', 'asset_code'], name='telemetry_a_asset_t_993657_idx'),
        ),
        migrations.AddIndex(
            model_name='assetidentity',
            index=models.Index(fields=['external_id_type', 'external_id'], name='telemetry_a_externa_382aef_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetidentity',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='unique_telemetry_source_external_id'),
        ),
    ]
