# Generated by Django 5.2.14 on 2026-05-17 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestAssetState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('tug', 'Tug'), ('barge', 'Barge'), ('cts', 'CTS'), ('ogv', 'OGV'), ('service_boat', 'Service boat')], max_length=32)),
                ('asset_code', models.CharField(max_length=80)),
                ('derived_status', models.CharField(choices=[('underway', 'Underway'), ('stopped', 'Stopped'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('speed_knots', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('heading_degrees', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('freshness_status', models.CharField(choices=[('fresh', 'Fresh'), ('aging', 'Aging'), ('stale', 'Stale'), ('missing', 'Missing')], default='missing', max_length=32)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('paired_asset_code', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='latest_states', to='telemetry.assetidentity')),
                ('last_ping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_state_refs', to='telemetry.positionping')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='latest_asset_states', to='telemetry.telemetrysource')),
            ],
            options={
                'ordering': ['asset_type', 'asset_code'],
                'indexes': [models.Index(fields=['freshness_status', 'last_seen_at'], name='telemetry_l_freshne_2f6708_idx'), models.Index(fields=['asset_type', 'asset_code'], name='telemetry_l_asset_t_0eef2b_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset_type', 'asset_code'), name='unique_latest_asset_state')],
            },
        ),
    ]
