# Generated by Django 5.2.14 on 2026-05-17 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
        ('telemetry', '0003_backfill_latest_asset_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeofenceZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.CharField(max_length=96, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('zone_type', models.CharField(choices=[('mine', 'Mine'), ('cpp', 'CPP'), ('jetty', 'Jetty'), ('checkpoint', 'Checkpoint'), ('bridge', 'Bridge'), ('tide_gate', 'Tide gate'), ('anchorage', 'Anchorage'), ('transshipment', 'Transshipment'), ('cts_zone', 'CTS zone'), ('maintenance', 'Maintenance')], max_length=40)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('radius_m', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('retired', 'Retired')], default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telemetry_geofences', to='masters.location')),
            ],
            options={
                'ordering': ['zone_type', 'zone_id'],
            },
        ),
        migrations.AddField(
            model_name='latestassetstate',
            name='current_geofence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_asset_states', to='telemetry.geofencezone'),
        ),
        migrations.CreateModel(
            name='MovementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=96, unique=True)),
                ('event_type', models.CharField(choices=[('enter_geofence', 'Enter geofence'), ('exit_geofence', 'Exit geofence')], max_length=40)),
                ('asset_type', models.CharField(choices=[('tug', 'Tug'), ('barge', 'Barge'), ('cts', 'CTS'), ('ogv', 'OGV'), ('service_boat', 'Service boat')], max_length=32)),
                ('asset_code', models.CharField(max_length=80)),
                ('event_at', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('speed_knots', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset_identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_events', to='telemetry.assetidentity')),
                ('geofence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_events', to='telemetry.geofencezone')),
                ('position_ping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_events', to='telemetry.positionping')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_events', to='telemetry.telemetrysource')),
            ],
            options={
                'ordering': ['-event_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='latestassetstate',
            name='last_movement_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_state_refs', to='telemetry.movementevent'),
        ),
        migrations.AddIndex(
            model_name='geofencezone',
            index=models.Index(fields=['status', 'zone_type'], name='telemetry_g_status_2119a8_idx'),
        ),
        migrations.AddIndex(
            model_name='geofencezone',
            index=models.Index(fields=['zone_id'], name='telemetry_g_zone_id_6717f9_idx'),
        ),
        migrations.AddIndex(
            model_name='movementevent',
            index=models.Index(fields=['asset_code', 'event_at'], name='telemetry_m_asset_c_569c79_idx'),
        ),
        migrations.AddIndex(
            model_name='movementevent',
            index=models.Index(fields=['event_type', 'event_at'], name='telemetry_m_event_t_7cba7f_idx'),
        ),
        migrations.AddIndex(
            model_name='movementevent',
            index=models.Index(fields=['geofence', 'event_at'], name='telemetry_m_geofenc_f2254e_idx'),
        ),
        migrations.AddConstraint(
            model_name='movementevent',
            constraint=models.UniqueConstraint(fields=('position_ping', 'geofence', 'event_type'), name='unique_ping_geofence_movement_event'),
        ),
    ]
