# Generated by Django 5.2.14 on 2026-05-18 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_alter_exportjob_export_type'),
        ('telemetry', '0005_backfill_geofence_zones'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveEtaProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projection_id', models.CharField(max_length=96, unique=True)),
                ('asset_type', models.CharField(choices=[('tug', 'Tug'), ('barge', 'Barge'), ('cts', 'CTS'), ('ogv', 'OGV'), ('service_boat', 'Service boat')], max_length=32)),
                ('asset_code', models.CharField(max_length=80)),
                ('planned_at', models.DateTimeField()),
                ('observed_eta', models.DateTimeField(blank=True, null=True)),
                ('variance_minutes', models.IntegerField(blank=True, null=True)),
                ('calculation_method', models.CharField(choices=[('route_remaining', 'Route remaining'), ('geofence_sequence', 'Geofence sequence'), ('simple_speed', 'Simple speed'), ('synthetic_script', 'Synthetic script')], default='simple_speed', max_length=40)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('on_time', 'On time'), ('watch', 'Watch'), ('delayed', 'Delayed'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eta_projections', to='telemetry.assetidentity')),
                ('current_geofence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eta_projections', to='telemetry.geofencezone')),
                ('schedule_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_eta_projections', to='scheduling.scheduleevent')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eta_projections', to='telemetry.telemetrysource')),
                ('source_ping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eta_projections', to='telemetry.positionping')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_eta_projections', to='scheduling.trip')),
            ],
            options={
                'ordering': ['-calculated_at', 'asset_code'],
            },
        ),
        migrations.CreateModel(
            name='TrackingAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(max_length=96, unique=True)),
                ('alert_type', models.CharField(choices=[('delay', 'Delay'), ('stale_signal', 'Stale signal'), ('route_deviation', 'Route deviation'), ('geofence_dwell', 'Geofence dwell'), ('missing_asset', 'Missing asset'), ('eta_risk', 'ETA risk')], max_length=40)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=32)),
                ('asset_type', models.CharField(choices=[('tug', 'Tug'), ('barge', 'Barge'), ('cts', 'CTS'), ('ogv', 'OGV'), ('service_boat', 'Service boat')], max_length=32)),
                ('asset_code', models.CharField(max_length=80)),
                ('message', models.CharField(max_length=255)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('converted_to_scenario', 'Converted to scenario'), ('dismissed', 'Dismissed'), ('resolved', 'Resolved')], default='open', max_length=40)),
                ('source_kind', models.CharField(choices=[('synthetic', 'Synthetic'), ('observed', 'Observed'), ('vendor', 'Vendor')], default='observed', max_length=32)),
                ('opened_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracking_alerts', to='telemetry.assetidentity')),
                ('created_scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_tracking_alerts', to='scheduling.simulationscenario')),
                ('eta_projection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_alerts', to='telemetry.liveetaprojection')),
                ('schedule_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_alerts', to='scheduling.scheduleevent')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracking_alerts', to='telemetry.telemetrysource')),
                ('source_ping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_alerts', to='telemetry.positionping')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_alerts', to='scheduling.trip')),
            ],
            options={
                'ordering': ['-opened_at', 'severity', 'asset_code'],
            },
        ),
        migrations.AddIndex(
            model_name='liveetaprojection',
            index=models.Index(fields=['asset_code', 'status'], name='telemetry_l_asset_c_fb9ca3_idx'),
        ),
        migrations.AddIndex(
            model_name='liveetaprojection',
            index=models.Index(fields=['trip', 'status'], name='telemetry_l_trip_id_1c999d_idx'),
        ),
        migrations.AddIndex(
            model_name='liveetaprojection',
            index=models.Index(fields=['schedule_event', 'status'], name='telemetry_l_schedul_60893b_idx'),
        ),
        migrations.AddConstraint(
            model_name='liveetaprojection',
            constraint=models.UniqueConstraint(fields=('asset_code', 'trip', 'schedule_event'), name='unique_live_eta_asset_trip_event'),
        ),
        migrations.AddIndex(
            model_name='trackingalert',
            index=models.Index(fields=['status', 'severity', 'opened_at'], name='telemetry_t_status_c0d842_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingalert',
            index=models.Index(fields=['asset_code', 'status', 'alert_type'], name='telemetry_t_asset_c_2c7e67_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingalert',
            index=models.Index(fields=['trip', 'status', 'alert_type'], name='telemetry_t_trip_id_9a48e2_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingalert',
            index=models.Index(fields=['source_kind', 'status'], name='telemetry_t_source__ba255f_idx'),
        ),
    ]
