# Generated by Django 5.2.14 on 2026-05-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0006_liveetaprojection_trackingalert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryReplayRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replay_id', models.CharField(max_length=96, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='draft', max_length=32)),
                ('scenario_code', models.CharField(max_length=80)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('speed_multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('seed_start_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scenario_code', 'replay_id'],
                'indexes': [models.Index(fields=['status', 'scenario_code'], name='telemetry_t_status_4fc28c_idx'), models.Index(fields=['started_at', 'completed_at'], name='telemetry_t_started_a92a87_idx')],
            },
        ),
    ]
