# Generated by Django 5.2.14 on 2026-05-29 21:51

import apps.telemetry.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0007_telemetryreplayrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryTrustProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_key', models.CharField(max_length=96, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deprecated', 'Deprecated')], default='active', max_length=32)),
                ('source_hierarchy', models.JSONField(blank=True, default=list)),
                ('freshness_thresholds', models.JSONField(blank=True, default=dict)),
                ('confidence_thresholds', models.JSONField(blank=True, default=dict)),
                ('identity_rules', models.JSONField(blank=True, default=dict)),
                ('quarantine_rules', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['profile_key', '-version'],
                'indexes': [models.Index(fields=['profile_key', 'status'], name='telemetry_t_profile_ae6aa4_idx'), models.Index(fields=['status', 'version'], name='telemetry_t_status_1b69f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='TelemetryTrustAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_id', models.CharField(default=apps.telemetry.models.telemetry_trust_assessment_reference, max_length=96, unique=True)),
                ('asset_type', models.CharField(choices=[('tug', 'Tug'), ('barge', 'Barge'), ('cts', 'CTS'), ('ogv', 'OGV'), ('service_boat', 'Service boat')], max_length=32)),
                ('asset_code', models.CharField(max_length=80)),
                ('trust_status', models.CharField(choices=[('trusted', 'Trusted'), ('degraded', 'Degraded'), ('quarantined', 'Quarantined'), ('manual_confirmation_required', 'Manual confirmation required'), ('unknown', 'Unknown')], default='unknown', max_length=48)),
                ('freshness_status', models.CharField(blank=True, max_length=32)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('identity_match_status', models.CharField(choices=[('matched', 'Matched'), ('ambiguous', 'Ambiguous'), ('unmapped', 'Unmapped'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('source_rank', models.PositiveIntegerField(default=999)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('assessed_at', models.DateTimeField()),
                ('algorithm_version', models.CharField(max_length=96)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset_identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trust_assessments', to='telemetry.assetidentity')),
                ('latest_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trust_assessments', to='telemetry.latestassetstate')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trust_assessments', to='telemetry.telemetrysource')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='telemetry.telemetrytrustprofile')),
            ],
            options={
                'ordering': ['-assessed_at', '-id'],
                'indexes': [models.Index(fields=['trust_status', 'assessed_at'], name='telemetry_t_trust_s_dc41af_idx'), models.Index(fields=['asset_type', 'asset_code', 'assessed_at'], name='telemetry_t_asset_t_d1320e_idx'), models.Index(fields=['source', 'trust_status'], name='telemetry_t_source__0577f2_idx'), models.Index(fields=['profile', 'trust_status'], name='telemetry_t_profile_0ee891_idx')],
            },
        ),
    ]
