# Generated by Django 5.2.14 on 2026-05-18 10:31

import apps.operations.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('scheduling', '0010_simulationscenario_metadata_source_kind'),
        ('telemetry', '0007_telemetryreplayrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedOperationalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(default=apps.operations.models.confirmed_event_reference, max_length=96, unique=True)),
                ('event_kind', models.CharField(choices=[('jetty_arrived', 'Jetty arrived'), ('jetty_loading_started', 'Jetty loading started'), ('jetty_loading_completed', 'Jetty loading completed'), ('jetty_departed', 'Jetty departed'), ('bridge_opened', 'Bridge opened'), ('bridge_closed', 'Bridge closed'), ('bridge_crossed', 'Bridge crossed'), ('tide_level_observed', 'Tide level observed'), ('tide_gate_passed', 'Tide gate passed'), ('cts_arrived', 'CTS arrived'), ('cts_discharge_started', 'CTS discharge started'), ('cts_rate_updated', 'CTS rate updated'), ('cts_discharge_stopped', 'CTS discharge stopped'), ('cts_discharge_completed', 'CTS discharge completed'), ('equipment_breakdown', 'Equipment breakdown'), ('device_offline', 'Device offline'), ('manual_status_update', 'Manual status update')], max_length=48)),
                ('actual_at', models.DateTimeField()),
                ('confirmed_quantity_mt', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('confirmed_rate_tph', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('confirmed_grade_code', models.CharField(blank=True, max_length=80)),
                ('confirmed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmation_mode', models.CharField(choices=[('manual', 'Manual'), ('auto_trusted_source', 'Auto trusted source'), ('auto_threshold', 'Auto threshold'), ('replay_proof', 'Replay proof')], default='manual', max_length=40)),
                ('reason_code', models.CharField(blank=True, max_length=80)),
                ('before_state', models.JSONField(blank=True, default=dict)),
                ('after_state', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_operational_events', to='scheduling.assignment')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_operational_events', to=settings.AUTH_USER_MODEL)),
                ('plan_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_operational_events', to='scheduling.planversion')),
                ('schedule_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_operational_events', to='scheduling.scheduleevent')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_operational_events', to='scheduling.trip')),
            ],
            options={
                'ordering': ['-actual_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.CharField(max_length=96, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('feed_type', models.CharField(choices=[('synthetic', 'Synthetic'), ('mqtt', 'MQTT'), ('http', 'HTTP'), ('plc', 'PLC'), ('weighbridge', 'Weighbridge'), ('tide_sensor', 'Tide sensor'), ('bridge_operator', 'Bridge operator'), ('jetty_operator', 'Jetty operator'), ('cts_operator', 'CTS operator'), ('manual', 'Manual')], max_length=40)),
                ('status', models.CharField(choices=[('active', 'Active'), ('degraded', 'Degraded'), ('paused', 'Paused'), ('retired', 'Retired')], default='active', max_length=32)),
                ('trust_mode', models.CharField(choices=[('manual_review', 'Manual review'), ('auto_confirm', 'Auto-confirm'), ('auto_confirm_with_threshold', 'Auto-confirm with threshold')], default='manual_review', max_length=40)),
                ('freshness_threshold_seconds', models.PositiveIntegerField(default=900)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['feed_id'],
                'indexes': [models.Index(fields=['feed_type', 'status'], name='operations__feed_ty_b117db_idx'), models.Index(fields=['trust_mode', 'status'], name='operations__trust_m_82128d_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=96, unique=True)),
                ('device_type', models.CharField(choices=[('edge_gateway', 'Edge gateway'), ('jetty_plc', 'Jetty PLC'), ('weighbridge', 'Weighbridge'), ('operator_tablet', 'Operator tablet'), ('tide_sensor', 'Tide sensor'), ('bridge_console', 'Bridge console'), ('cts_plc', 'CTS PLC'), ('ais_receiver', 'AIS receiver'), ('gps_tracker', 'GPS tracker')], max_length=40)),
                ('asset_type', models.CharField(blank=True, choices=[('tug', 'Tug'), ('barge', 'Barge'), ('cts', 'CTS'), ('ogv', 'OGV'), ('jetty', 'Jetty'), ('bridge', 'Bridge'), ('tide_gate', 'Tide gate'), ('device', 'Device'), ('other', 'Other')], max_length=32)),
                ('asset_code', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('active', 'Active'), ('degraded', 'Degraded'), ('offline', 'Offline'), ('paused', 'Paused'), ('retired', 'Retired')], default='active', max_length=32)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geofence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_devices', to='telemetry.geofencezone')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_devices', to='masters.location')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='operations.integrationfeed')),
            ],
            options={
                'ordering': ['device_type', 'device_id'],
            },
        ),
        migrations.CreateModel(
            name='OperationalActualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualization_id', models.CharField(default=apps.operations.models.actualization_reference, max_length=96, unique=True)),
                ('target_type', models.CharField(choices=[('schedule_event', 'Schedule event'), ('trip', 'Trip'), ('assignment', 'Assignment'), ('constraint_window', 'Constraint window'), ('asset_health', 'Asset health')], max_length=40)),
                ('target_id', models.CharField(blank=True, max_length=120)),
                ('before_state', models.JSONField(blank=True, default=dict)),
                ('after_state', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='skipped', max_length=32)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualizations', to='operations.confirmedoperationalevent')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OperationalEventCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(default=apps.operations.models.candidate_reference, max_length=96, unique=True)),
                ('source_kind', models.CharField(choices=[('synthetic', 'Synthetic'), ('device', 'Device'), ('operator', 'Operator'), ('telemetry_inferred', 'Telemetry inferred'), ('vendor', 'Vendor')], max_length=32)),
                ('event_kind', models.CharField(choices=[('jetty_arrived', 'Jetty arrived'), ('jetty_loading_started', 'Jetty loading started'), ('jetty_loading_completed', 'Jetty loading completed'), ('jetty_departed', 'Jetty departed'), ('bridge_opened', 'Bridge opened'), ('bridge_closed', 'Bridge closed'), ('bridge_crossed', 'Bridge crossed'), ('tide_level_observed', 'Tide level observed'), ('tide_gate_passed', 'Tide gate passed'), ('cts_arrived', 'CTS arrived'), ('cts_discharge_started', 'CTS discharge started'), ('cts_rate_updated', 'CTS rate updated'), ('cts_discharge_stopped', 'CTS discharge stopped'), ('cts_discharge_completed', 'CTS discharge completed'), ('equipment_breakdown', 'Equipment breakdown'), ('device_offline', 'Device offline'), ('manual_status_update', 'Manual status update')], max_length=48)),
                ('asset_type', models.CharField(blank=True, choices=[('tug', 'Tug'), ('barge', 'Barge'), ('cts', 'CTS'), ('ogv', 'OGV'), ('jetty', 'Jetty'), ('bridge', 'Bridge'), ('tide_gate', 'Tide gate'), ('device', 'Device'), ('other', 'Other')], max_length=32)),
                ('asset_code', models.CharField(blank=True, max_length=80)),
                ('event_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('dedupe_key', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('auto_confirmed', 'Auto-confirmed'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('superseded', 'Superseded'), ('duplicate', 'Duplicate')], default='pending', max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('raw_payload_ref', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_event_candidates', to='scheduling.assignment')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_candidates', to='operations.deviceendpoint')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_candidates', to='operations.integrationfeed')),
                ('schedule_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_event_candidates', to='scheduling.scheduleevent')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_event_candidates', to='scheduling.trip')),
            ],
            options={
                'ordering': ['-event_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='confirmedoperationalevent',
            name='candidate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_event', to='operations.operationaleventcandidate'),
        ),
        migrations.CreateModel(
            name='DeviceHealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_id', models.CharField(default=apps.operations.models.snapshot_reference, max_length=96, unique=True)),
                ('observed_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('critical', 'Critical'), ('offline', 'Offline'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('battery_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('power_status', models.CharField(blank=True, max_length=80)),
                ('network_status', models.CharField(blank=True, max_length=80)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('gap_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_snapshots', to='operations.deviceendpoint')),
            ],
            options={
                'ordering': ['-observed_at', '-id'],
                'indexes': [models.Index(fields=['device', 'observed_at'], name='operations__device__81474d_idx'), models.Index(fields=['health_status', 'observed_at'], name='operations__health__9d1de5_idx')],
            },
        ),
        migrations.CreateModel(
            name='EdgeEventBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(default=apps.operations.models.batch_reference, max_length=96, unique=True)),
                ('batch_sequence', models.CharField(blank=True, max_length=120)),
                ('captured_from', models.DateTimeField(blank=True, null=True)),
                ('captured_to', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('partial', 'Partial'), ('failed', 'Failed')], default='received', max_length=32)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edge_batches', to='operations.deviceendpoint')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edge_batches', to='operations.integrationfeed')),
            ],
            options={
                'ordering': ['-received_at', '-id'],
                'indexes': [models.Index(fields=['feed', 'status', 'received_at'], name='operations__feed_id_c0115b_idx'), models.Index(fields=['device', 'received_at'], name='operations__device__b1cb67_idx'), models.Index(fields=['batch_sequence'], name='operations__batch_s_9a6e5e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='deviceendpoint',
            index=models.Index(fields=['status', 'device_type'], name='operations__status_0029ae_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceendpoint',
            index=models.Index(fields=['asset_type', 'asset_code'], name='operations__asset_t_3c2b12_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceendpoint',
            index=models.Index(fields=['last_seen_at'], name='operations__last_se_69e57c_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalactualization',
            index=models.Index(fields=['confirmed_event', 'status'], name='operations__confirm_beba64_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalactualization',
            index=models.Index(fields=['target_type', 'target_id'], name='operations__target__d55069_idx'),
        ),
        migrations.AddIndex(
            model_name='operationaleventcandidate',
            index=models.Index(fields=['status', 'event_kind', 'event_at'], name='operations__status_821a07_idx'),
        ),
        migrations.AddIndex(
            model_name='operationaleventcandidate',
            index=models.Index(fields=['asset_type', 'asset_code', 'event_at'], name='operations__asset_t_0380a9_idx'),
        ),
        migrations.AddIndex(
            model_name='operationaleventcandidate',
            index=models.Index(fields=['trip', 'event_kind'], name='operations__trip_id_f4a1ab_idx'),
        ),
        migrations.AddIndex(
            model_name='operationaleventcandidate',
            index=models.Index(fields=['schedule_event', 'event_kind'], name='operations__schedul_ae5453_idx'),
        ),
        migrations.AddConstraint(
            model_name='operationaleventcandidate',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('feed', 'dedupe_key'), name='unique_operational_candidate_dedupe_key'),
        ),
        migrations.AddIndex(
            model_name='confirmedoperationalevent',
            index=models.Index(fields=['event_kind', 'actual_at'], name='operations__event_k_71d38e_idx'),
        ),
        migrations.AddIndex(
            model_name='confirmedoperationalevent',
            index=models.Index(fields=['plan_version', 'event_kind', 'actual_at'], name='operations__plan_ve_0489da_idx'),
        ),
        migrations.AddIndex(
            model_name='confirmedoperationalevent',
            index=models.Index(fields=['trip', 'event_kind'], name='operations__trip_id_a1df9f_idx'),
        ),
        migrations.AddIndex(
            model_name='confirmedoperationalevent',
            index=models.Index(fields=['schedule_event', 'event_kind'], name='operations__schedul_c5e77f_idx'),
        ),
    ]
