# Generated by Django 5.2.14 on 2026-05-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        ('scheduling', '0010_simulationscenario_metadata_source_kind'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='operationaleventcandidate',
            name='unique_operational_candidate_dedupe_key',
        ),
        migrations.AddIndex(
            model_name='operationaleventcandidate',
            index=models.Index(fields=['feed', 'dedupe_key'], name='operations__feed_id_629f52_idx'),
        ),
    ]
