# Generated by Django 5.2.14 on 2026-05-15 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('organizations', '0001_initial'),
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('horizon_start', models.DateTimeField()),
                ('horizon_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='organizations.organization')),
            ],
            options={
                'ordering': ['-horizon_start', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('validated', 'Validated'), ('proposed', 'Proposed'), ('approved', 'Approved'), ('published', 'Published')], default='draft', max_length=32)),
                ('validation_status', models.CharField(choices=[('feasible', 'Feasible'), ('warning', 'Warning'), ('blocked', 'Blocked')], default='feasible', max_length=32)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plan_versions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='scheduling.plan')),
                ('source_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successor_versions', to='scheduling.planversion')),
            ],
            options={
                'ordering': ['plan__code', '-version_no'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=80)),
                ('sequence', models.PositiveIntegerField()),
                ('planned_start', models.DateTimeField()),
                ('planned_end', models.DateTimeField()),
                ('planned_quantity_mt', models.PositiveIntegerField()),
                ('loaded_quantity_mt', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('loading', 'Loading'), ('transit', 'Transit'), ('discharging', 'Discharging'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='planned', max_length=32)),
                ('selection_reason', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cargo_layer_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_trips', to='planning.cargolayerstep')),
                ('cargo_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_trips', to='planning.cargorequirement')),
                ('destination_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_trips', to='masters.location')),
                ('origin_jetty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origin_trips', to='masters.jetty')),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='scheduling.planversion')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_trips', to='planning.ogvvoyage')),
            ],
            options={
                'ordering': ['plan_version', 'sequence', 'trip_id'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('event_type', models.CharField(choices=[('load_start', 'Load start'), ('load_complete', 'Load complete'), ('depart_jetty', 'Depart jetty'), ('bridge_cross', 'Bridge cross'), ('tide_gate', 'Tide gate'), ('arrive_cts', 'Arrive CTS'), ('discharge_start', 'Discharge start'), ('discharge_complete', 'Discharge complete')], max_length=40)),
                ('planned_at', models.DateTimeField()),
                ('actual_at', models.DateTimeField(blank=True, null=True)),
                ('location_label', models.CharField(blank=True, max_length=120)),
                ('resource_code', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('actual', 'Actual'), ('delayed', 'Delayed'), ('missed', 'Missed')], default='planned', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='scheduling.trip')),
            ],
            options={
                'ordering': ['trip', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=32)),
                ('object_type', models.CharField(blank=True, max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=80)),
                ('message', models.CharField(max_length=255)),
                ('is_blocking', models.BooleanField(default=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='scheduling.planversion')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='scheduling.trip')),
            ],
            options={
                'ordering': ['-is_blocking', 'severity', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_departure', models.DateTimeField()),
                ('planned_arrival', models.DateTimeField()),
                ('tug_status', models.CharField(blank=True, max_length=80)),
                ('barge_status', models.CharField(blank=True, max_length=80)),
                ('next_constraint', models.CharField(blank=True, max_length=180)),
                ('next_action', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('waiting_tide', 'Waiting tide'), ('waiting_bridge', 'Waiting bridge'), ('loading', 'Loading'), ('in_transit', 'In transit'), ('at_cts', 'At CTS'), ('blocked', 'Blocked')], default='assigned', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_assignments', to='masters.barge')),
                ('cts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_assignments', to='masters.ctsasset')),
                ('jetty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_assignments', to='masters.jetty')),
                ('owner_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_assignments', to='organizations.organization')),
                ('route_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_assignments', to='masters.routesegment')),
                ('tug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_assignments', to='masters.tug')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='scheduling.trip')),
            ],
            options={
                'ordering': ['planned_departure', 'trip__trip_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='planversion',
            constraint=models.UniqueConstraint(fields=('plan', 'version_no'), name='unique_plan_version_no'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(fields=('plan_version', 'trip_id'), name='unique_plan_version_trip_id'),
        ),
        migrations.AddConstraint(
            model_name='scheduleevent',
            constraint=models.UniqueConstraint(fields=('trip', 'sequence'), name='unique_trip_event_sequence'),
        ),
        migrations.AddIndex(
            model_name='conflict',
            index=models.Index(fields=['code', 'severity', 'is_blocking'], name='scheduling__code_d8b708_idx'),
        ),
    ]
