# Generated by Django 5.2.14 on 2026-05-15 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='planversion',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('validated', 'Validated'), ('proposed', 'Proposed'), ('approved', 'Approved'), ('published', 'Published'), ('superseded', 'Superseded')], default='draft', max_length=32),
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=80, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('canceled', 'Canceled')], default='pending', max_length=32)),
                ('required_authorities', models.JSONField(blank=True, default=list)),
                ('reason', models.CharField(max_length=255)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='scheduling.planversion')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_plan_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_role', models.CharField(choices=[('berau_scheduler', 'Berau Scheduler'), ('abl_dispatcher', 'ABL Dispatcher'), ('joint_control', 'Joint Control')], max_length=64)),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('return', 'Return'), ('escalate', 'Escalate')], max_length=32)),
                ('comments', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_approval_decisions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_approval_decisions', to='organizations.organization')),
                ('approval_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='scheduling.approvalrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OverrideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_code', models.CharField(choices=[('tug_breakdown', 'Tug breakdown'), ('barge_unavailable', 'Barge unavailable'), ('jetty_delay', 'Jetty delay'), ('tide_bridge_recovery', 'Tide / bridge recovery'), ('grade_sequence_recovery', 'Grade sequence recovery'), ('manual_correction', 'Manual correction')], max_length=64)),
                ('description', models.CharField(max_length=255)),
                ('requested_change', models.JSONField(blank=True, default=dict)),
                ('before_state', models.JSONField(blank=True, default=dict)),
                ('after_state', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], default='pending', max_length=32)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_schedule_overrides', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='override_requests', to='scheduling.assignment')),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='override_requests', to='scheduling.planversion')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_schedule_overrides', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='override_requests', to='scheduling.trip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublishedPlanSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_id', models.CharField(max_length=80, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded')], default='active', max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('approval_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_snapshots', to='scheduling.approvalrequest')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_snapshots', to='scheduling.plan')),
                ('plan_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='published_snapshot', to='scheduling.planversion')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_plan_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_id', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('scenario_type', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('simulated', 'Simulated'), ('proposed', 'Proposed'), ('canceled', 'Canceled')], default='draft', max_length=32)),
                ('recovery_actions', models.JSONField(blank=True, default=list)),
                ('impact_summary', models.JSONField(blank=True, default=dict)),
                ('delta_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baseline_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseline_scenarios', to='scheduling.planversion')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_simulation_scenarios', to=settings.AUTH_USER_MODEL)),
                ('scenario_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenario_outputs', to='scheduling.planversion')),
                ('source_conflict', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_scenarios', to='scheduling.conflict')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['status', 'created_at'], name='scheduling__status_ad8166_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvaldecision',
            constraint=models.UniqueConstraint(fields=('approval_request', 'authority_role'), name='unique_approval_decision_authority'),
        ),
        migrations.AddIndex(
            model_name='overriderequest',
            index=models.Index(fields=['plan_version', 'status', 'reason_code'], name='scheduling__plan_ve_8d7af3_idx'),
        ),
        migrations.AddIndex(
            model_name='publishedplansnapshot',
            index=models.Index(fields=['plan', 'status'], name='scheduling__plan_id_3df771_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationscenario',
            index=models.Index(fields=['status', 'created_at'], name='scheduling__status_9e9b40_idx'),
        ),
    ]
