# Generated by Django 5.2.14 on 2026-05-16 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('scheduling', '0002_alter_planversion_status_approvalrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_id', models.CharField(max_length=96, unique=True)),
                ('export_type', models.CharField(choices=[('plan', 'Plan'), ('conflict', 'Conflict'), ('audit', 'Audit')], max_length=32)),
                ('export_format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('print', 'Printable text')], max_length=16)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('failed', 'Failed')], default='generated', max_length=32)),
                ('storage_bucket', models.CharField(max_length=120)),
                ('storage_key', models.CharField(max_length=512)),
                ('file_name', models.CharField(max_length=220)),
                ('content_type', models.CharField(max_length=120)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_export_jobs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_exports', to='organizations.organization')),
                ('plan_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='export_jobs', to='scheduling.planversion')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['export_type', 'status', 'created_at'], name='scheduling__export__1244bd_idx'), models.Index(fields=['organization', 'created_at'], name='scheduling__organiz_bbb897_idx')],
            },
        ),
    ]
