# Generated by Django 5.2.14 on 2026-05-16 02:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
        ('organizations', '0001_initial'),
        ('planning', '0002_assetavailabilitywindow_planning_as_asset_t_71225f_idx_and_more'),
        ('scheduling', '0003_exportjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['plan_version', 'status', 'created_at'], name='scheduling__plan_ve_5d9e3f_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['status', 'planned_departure'], name='scheduling__status_b86502_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['owner_organization', 'planned_departure'], name='scheduling__owner_o_567c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='publishedplansnapshot',
            index=models.Index(fields=['status', 'published_at'], name='scheduling__status_ffd196_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleevent',
            index=models.Index(fields=['planned_at', 'status'], name='scheduling__planned_891f24_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleevent',
            index=models.Index(fields=['resource_code', 'planned_at'], name='scheduling__resourc_d3f179_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['plan_version', 'status', 'planned_start'], name='scheduling__plan_ve_bf54be_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['plan_version', 'planned_start'], name='scheduling__plan_ve_393015_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['voyage', 'plan_version'], name='scheduling__voyage__66a3c2_idx'),
        ),
    ]
