# Generated by Django 5.2.14 on 2026-05-17 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_existing_source_kinds(apps, schema_editor):
    SimulationScenario = apps.get_model("scheduling", "SimulationScenario")
    SimulationScenario.objects.filter(source_conflict__isnull=False).update(
        source_kind="conflict"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_impactchainassessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationscenario',
            name='source_kind',
            field=models.CharField(choices=[('manual', 'Manual'), ('conflict', 'Conflict'), ('override', 'Override')], default='manual', max_length=32),
        ),
        migrations.AddField(
            model_name='simulationscenario',
            name='source_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_scenarios', to='scheduling.overriderequest'),
        ),
        migrations.RunPython(backfill_existing_source_kinds, migrations.RunPython.noop),
        migrations.CreateModel(
            name='ScenarioAssumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assumption_id', models.CharField(max_length=96, unique=True)),
                ('kind', models.CharField(choices=[('trip_delay', 'Trip delay'), ('asset_outage', 'Asset outage'), ('rate_change', 'Rate change'), ('window_change', 'Window change'), ('ogv_eta_change', 'OGV ETA change'), ('manual_reassignment', 'Manual reassignment')], max_length=48)),
                ('scope_type', models.CharField(choices=[('trip', 'Trip'), ('assignment', 'Assignment'), ('asset', 'Asset'), ('window', 'Window'), ('ogv', 'OGV')], max_length=32)),
                ('scope_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scenario_assumptions', to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assumptions', to='scheduling.simulationscenario')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['scenario', 'kind', 'created_at'], name='scheduling__scenari_82c382_idx'), models.Index(fields=['scope_type', 'scope_id'], name='scheduling__scope_t_6c08f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScenarioRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=96, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='queued', max_length=32)),
                ('algorithm_version', models.CharField(max_length=80)),
                ('input_hash', models.CharField(max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baseline_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_runs', to='scheduling.planversion')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scenario_runs', to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='scheduling.simulationscenario')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['scenario', 'status', 'created_at'], name='scheduling__scenari_024398_idx'), models.Index(fields=['baseline_version', 'created_at'], name='scheduling__baselin_874a9f_idx'), models.Index(fields=['input_hash'], name='scheduling__input_h_b789be_idx')],
            },
        ),
    ]
