# Generated by Django 5.2.14 on 2026-05-17 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_simulationscenario_source_kind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioEventProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=40)),
                ('baseline_at', models.DateTimeField()),
                ('projected_at', models.DateTimeField()),
                ('projected_status', models.CharField(max_length=32)),
                ('delay_minutes', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_event_projections', to='scheduling.scheduleevent')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_projections', to='scheduling.scenariorun')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_event_projections', to='scheduling.trip')),
            ],
            options={
                'ordering': ['trip__sequence', 'event__sequence'],
                'indexes': [models.Index(fields=['run', 'projected_at'], name='scheduling__run_id_48fdaa_idx'), models.Index(fields=['trip', 'event_type'], name='scheduling__trip_id_557d41_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'event'), name='unique_scenario_run_event_projection')],
            },
        ),
        migrations.CreateModel(
            name='ScenarioTripProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_start', models.DateTimeField()),
                ('baseline_end', models.DateTimeField()),
                ('projected_start', models.DateTimeField()),
                ('projected_end', models.DateTimeField()),
                ('projected_status', models.CharField(max_length=32)),
                ('delay_minutes', models.IntegerField(default=0)),
                ('assignment_delta', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_projections', to='scheduling.scenariorun')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_trip_projections', to='scheduling.trip')),
            ],
            options={
                'ordering': ['trip__sequence', 'trip__trip_id'],
                'indexes': [models.Index(fields=['run', 'projected_start'], name='scheduling__run_id_caba55_idx'), models.Index(fields=['trip', 'delay_minutes'], name='scheduling__trip_id_cf0947_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'trip'), name='unique_scenario_run_trip_projection')],
            },
        ),
    ]
