# Generated by Django 5.2.14 on 2026-05-17 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_assetavailabilitywindow_planning_as_asset_t_71225f_idx_and_more'),
        ('scheduling', '0007_scenarioeventprojection_scenariotripprojection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioConstraintEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_id', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(max_length=80)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=32)),
                ('affected_object_type', models.CharField(max_length=48)),
                ('affected_object_id', models.CharField(blank=True, max_length=120)),
                ('baseline_value', models.JSONField(blank=True, default=dict)),
                ('projected_value', models.JSONField(blank=True, default=dict)),
                ('margin_minutes', models.IntegerField(blank=True, null=True)),
                ('source_assumption_ids', models.JSONField(blank=True, default=list)),
                ('message', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraint_evaluations', to='scheduling.scenariorun')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenario_constraint_evaluations', to='scheduling.trip')),
            ],
            options={
                'ordering': ['-severity', 'code', 'trip__sequence', 'id'],
                'indexes': [models.Index(fields=['run', 'severity', 'code'], name='scheduling__run_id_604721_idx'), models.Index(fields=['trip', 'severity'], name='scheduling__trip_id_bad1fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScenarioOgvProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_completion_at', models.DateTimeField()),
                ('projected_completion_at', models.DateTimeField()),
                ('completion_delta_minutes', models.IntegerField(default=0)),
                ('laycan_end', models.DateTimeField()),
                ('baseline_demurrage_minutes', models.IntegerField(default=0)),
                ('projected_demurrage_minutes', models.IntegerField(default=0)),
                ('demurrage_delta_usd', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('risk_status', models.CharField(choices=[('ok', 'OK'), ('warning', 'Warning'), ('critical', 'Critical')], default='ok', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ogv_projections', to='scheduling.scenariorun')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_ogv_projections', to='planning.ogvvoyage')),
            ],
            options={
                'ordering': ['voyage__laycan_start', 'voyage__voyage_id'],
                'indexes': [models.Index(fields=['run', 'risk_status'], name='scheduling__run_id_62ced3_idx'), models.Index(fields=['voyage', 'run'], name='scheduling__voyage__143cb2_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'voyage'), name='unique_scenario_run_ogv_projection')],
            },
        ),
        migrations.CreateModel(
            name='ScenarioResourceUtilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('tug', 'Tug'), ('barge', 'Barge'), ('jetty', 'Jetty'), ('cts', 'CTS')], max_length=32)),
                ('resource_code', models.CharField(max_length=80)),
                ('baseline_occupied_minutes', models.IntegerField(default=0)),
                ('projected_occupied_minutes', models.IntegerField(default=0)),
                ('baseline_idle_minutes', models.IntegerField(default=0)),
                ('projected_idle_minutes', models.IntegerField(default=0)),
                ('waiting_minutes', models.IntegerField(default=0)),
                ('utilization_delta_pct', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_utilizations', to='scheduling.scenariorun')),
            ],
            options={
                'ordering': ['resource_type', 'resource_code'],
                'indexes': [models.Index(fields=['run', 'resource_type'], name='scheduling__run_id_81dad3_idx'), models.Index(fields=['resource_type', 'resource_code'], name='scheduling__resourc_84da9c_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'resource_type', 'resource_code'), name='unique_scenario_run_resource_utilization')],
            },
        ),
    ]
