# Generated by Django 5.2.14 on 2026-05-18 13:49

import apps.scheduling.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_remove_operationaleventcandidate_unique_operational_candidate_dedupe_key_and_more'),
        ('scheduling', '0010_simulationscenario_metadata_source_kind'),
        ('telemetry', '0007_telemetryreplayrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryInputSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_id', models.CharField(default=apps.scheduling.models.recovery_snapshot_reference, max_length=96, unique=True)),
                ('source_kind', models.CharField(choices=[('manual', 'Manual'), ('conflict', 'Conflict'), ('override', 'Override'), ('tracking_alert', 'Tracking alert'), ('operational_event', 'Operational event'), ('scenario', 'Scenario')], default='manual', max_length=40)),
                ('source_ref', models.CharField(blank=True, max_length=120)),
                ('input_hash', models.CharField(blank=True, max_length=64)),
                ('active_conflict_count', models.PositiveIntegerField(default=0)),
                ('confirmed_event_count', models.PositiveIntegerField(default=0)),
                ('tracking_alert_count', models.PositiveIntegerField(default=0)),
                ('resource_state', models.JSONField(blank=True, default=dict)),
                ('event_state', models.JSONField(blank=True, default=dict)),
                ('constraint_state', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_recovery_input_snapshots', to=settings.AUTH_USER_MODEL)),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_input_snapshots', to='scheduling.planversion')),
                ('source_conflict', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_input_snapshots', to='scheduling.conflict')),
                ('source_operational_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_input_snapshots', to='operations.confirmedoperationalevent')),
                ('source_override', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_input_snapshots', to='scheduling.overriderequest')),
                ('source_scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_input_snapshots', to='scheduling.simulationscenario')),
                ('source_tracking_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_input_snapshots', to='telemetry.trackingalert')),
            ],
            options={
                'ordering': ['-generated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OptimizerRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(default=apps.scheduling.models.optimizer_run_reference, max_length=96, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='draft', max_length=32)),
                ('algorithm_version', models.CharField(default='phase5.0-foundation', max_length=80)),
                ('objective_weights', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimizer_runs', to='scheduling.planversion')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_optimizer_runs', to=settings.AUTH_USER_MODEL)),
                ('input_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimizer_runs', to='scheduling.recoveryinputsnapshot')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_id', models.CharField(default=apps.scheduling.models.recovery_recommendation_reference, max_length=96, unique=True)),
                ('rank', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('shortlisted', 'Shortlisted'), ('selected', 'Selected'), ('dismissed', 'Dismissed'), ('materialized', 'Materialized')], default='candidate', max_length=32)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=32)),
                ('score', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('summary', models.CharField(max_length=255)),
                ('explanation', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('optimizer_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='scheduling.optimizerrun')),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_recommendations', to='scheduling.simulationscenario')),
            ],
            options={
                'ordering': ['optimizer_run', 'rank', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.CharField(default=apps.scheduling.models.recovery_action_reference, max_length=96, unique=True)),
                ('sequence', models.PositiveIntegerField()),
                ('action_type', models.CharField(choices=[('delay_trip', 'Delay trip'), ('resequence_trip', 'Resequence trip'), ('reassign_tug', 'Reassign tug'), ('reassign_barge', 'Reassign barge'), ('reassign_cts', 'Reassign CTS'), ('shift_window', 'Shift window'), ('hold_at_anchorage', 'Hold at anchorage'), ('noop', 'No operation')], max_length=48)),
                ('before_state', models.JSONField(blank=True, default=dict)),
                ('after_state', models.JSONField(blank=True, default=dict)),
                ('constraints_checked', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_actions', to='scheduling.assignment')),
                ('target_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_actions', to='scheduling.trip')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='scheduling.recoveryrecommendation')),
            ],
            options={
                'ordering': ['recommendation', 'sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_id', models.CharField(default=apps.scheduling.models.recommendation_evaluation_reference, max_length=96, unique=True)),
                ('delay_minutes', models.IntegerField(default=0)),
                ('missed_windows', models.PositiveIntegerField(default=0)),
                ('resource_conflicts', models.PositiveIntegerField(default=0)),
                ('utilization_delta_pct', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('hard_constraints_passed', models.BooleanField(default=True)),
                ('score_breakdown', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='scheduling.recoveryrecommendation')),
            ],
            options={
                'ordering': ['recommendation__optimizer_run', 'recommendation__rank'],
            },
        ),
        migrations.AddIndex(
            model_name='recoveryinputsnapshot',
            index=models.Index(fields=['plan_version', 'source_kind', 'generated_at'], name='scheduling__plan_ve_52ed45_idx'),
        ),
        migrations.AddIndex(
            model_name='recoveryinputsnapshot',
            index=models.Index(fields=['source_kind', 'source_ref'], name='scheduling__source__daa36f_idx'),
        ),
        migrations.AddIndex(
            model_name='recoveryinputsnapshot',
            index=models.Index(fields=['input_hash'], name='scheduling__input_h_eaedb3_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizerrun',
            index=models.Index(fields=['plan_version', 'status', 'created_at'], name='scheduling__plan_ve_d4b048_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizerrun',
            index=models.Index(fields=['input_snapshot', 'status'], name='scheduling__input_s_6d8de1_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizerrun',
            index=models.Index(fields=['algorithm_version', 'status'], name='scheduling__algorit_5fdd18_idx'),
        ),
        migrations.AddIndex(
            model_name='recoveryrecommendation',
            index=models.Index(fields=['optimizer_run', 'status', 'rank'], name='scheduling__optimiz_4a772a_idx'),
        ),
        migrations.AddIndex(
            model_name='recoveryrecommendation',
            index=models.Index(fields=['risk_level', 'score'], name='scheduling__risk_le_c80a59_idx'),
        ),
        migrations.AddIndex(
            model_name='recoveryrecommendation',
            index=models.Index(fields=['status', 'created_at'], name='scheduling__status_e34cdf_idx'),
        ),
        migrations.AddConstraint(
            model_name='recoveryrecommendation',
            constraint=models.UniqueConstraint(fields=('optimizer_run', 'rank'), name='unique_optimizer_run_recommendation_rank'),
        ),
        migrations.AddIndex(
            model_name='recoveryaction',
            index=models.Index(fields=['recommendation', 'sequence'], name='scheduling__recomme_523bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='recoveryaction',
            index=models.Index(fields=['action_type', 'created_at'], name='scheduling__action__e8d4ca_idx'),
        ),
        migrations.AddIndex(
            model_name='recoveryaction',
            index=models.Index(fields=['target_trip', 'action_type'], name='scheduling__target__64fb75_idx'),
        ),
        migrations.AddConstraint(
            model_name='recoveryaction',
            constraint=models.UniqueConstraint(fields=('recommendation', 'sequence'), name='unique_recommendation_action_sequence'),
        ),
        migrations.AddIndex(
            model_name='recommendationevaluation',
            index=models.Index(fields=['hard_constraints_passed', 'confidence_score'], name='scheduling__hard_co_726bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationevaluation',
            index=models.Index(fields=['delay_minutes', 'missed_windows'], name='scheduling__delay_m_b730f3_idx'),
        ),
    ]
