# Generated by Django 5.2.14 on 2026-05-29 21:18

import apps.scheduling.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0013_publishabilityassessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalObjectiveProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_key', models.CharField(max_length=96, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deprecated', 'Deprecated')], default='active', max_length=32)),
                ('weights', models.JSONField(blank=True, default=dict)),
                ('constraints', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(default='settings', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['profile_key', '-version'],
                'indexes': [models.Index(fields=['profile_key', 'status'], name='scheduling__profile_97b8cf_idx'), models.Index(fields=['status', 'version'], name='scheduling__status_4b9ec2_idx')],
            },
        ),
        migrations.CreateModel(
            name='GlobalOptimizationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(default=apps.scheduling.models.global_optimization_run_reference, max_length=96, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='queued', max_length=32)),
                ('objective_weights', models.JSONField(blank=True, default=dict)),
                ('input_signature', models.CharField(blank=True, max_length=64)),
                ('input_summary', models.JSONField(blank=True, default=dict)),
                ('algorithm_version', models.CharField(default='phase6.5-global-optimizer-scaffold', max_length=96)),
                ('audit_lineage', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('objective_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='scheduling.globalobjectiveprofile')),
                ('plan_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='global_optimization_runs', to='scheduling.planversion')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_global_optimization_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GlobalOptimizationCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(default=apps.scheduling.models.global_optimization_candidate_reference, max_length=96, unique=True)),
                ('rank', models.PositiveIntegerField()),
                ('score', models.DecimalField(decimal_places=3, default=0, max_digits=9)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=32)),
                ('summary', models.CharField(max_length=255)),
                ('objective_score_breakdown', models.JSONField(blank=True, default=dict)),
                ('changed_assignments', models.JSONField(blank=True, default=list)),
                ('trip_sequence_changes', models.JSONField(blank=True, default=list)),
                ('projected_impacts', models.JSONField(blank=True, default=dict)),
                ('unresolved_risks', models.JSONField(blank=True, default=list)),
                ('approval_lineage', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='scheduling.globaloptimizationrun')),
            ],
            options={
                'ordering': ['run', 'rank', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='globaloptimizationrun',
            index=models.Index(fields=['status', 'created_at'], name='scheduling__status_505d8b_idx'),
        ),
        migrations.AddIndex(
            model_name='globaloptimizationrun',
            index=models.Index(fields=['plan_version', 'status', 'created_at'], name='scheduling__plan_ve_1d4587_idx'),
        ),
        migrations.AddIndex(
            model_name='globaloptimizationrun',
            index=models.Index(fields=['objective_profile', 'status'], name='scheduling__objecti_fd5760_idx'),
        ),
        migrations.AddIndex(
            model_name='globaloptimizationrun',
            index=models.Index(fields=['algorithm_version', 'status'], name='scheduling__algorit_539423_idx'),
        ),
        migrations.AddIndex(
            model_name='globaloptimizationrun',
            index=models.Index(fields=['input_signature'], name='scheduling__input_s_46241c_idx'),
        ),
        migrations.AddIndex(
            model_name='globaloptimizationcandidate',
            index=models.Index(fields=['run', 'rank'], name='scheduling__run_id_fdb619_idx'),
        ),
        migrations.AddIndex(
            model_name='globaloptimizationcandidate',
            index=models.Index(fields=['risk_level', 'score'], name='scheduling__risk_le_464cc6_idx'),
        ),
        migrations.AddIndex(
            model_name='globaloptimizationcandidate',
            index=models.Index(fields=['created_at'], name='scheduling__created_2ed59d_idx'),
        ),
        migrations.AddConstraint(
            model_name='globaloptimizationcandidate',
            constraint=models.UniqueConstraint(fields=('run', 'rank'), name='unique_global_optimization_candidate_rank'),
        ),
    ]
