# Generated by Django 5.2.14 on 2026-05-29 21:51

import apps.scheduling.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_assetavailabilitywindow_planning_as_asset_t_71225f_idx_and_more'),
        ('scheduling', '0014_globalobjectiveprofile_globaloptimizationrun_and_more'),
        ('telemetry', '0008_telemetrytrustprofile_telemetrytrustassessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialProjectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(default=apps.scheduling.models.commercial_projection_run_reference, max_length=96, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='queued', max_length=32)),
                ('input_signature', models.CharField(blank=True, max_length=64)),
                ('input_summary', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('algorithm_version', models.CharField(default='phase6.6-commercial-projection', max_length=96)),
                ('audit_lineage', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_commercial_projection_runs', to=settings.AUTH_USER_MODEL)),
                ('plan_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commercial_projection_runs', to='scheduling.planversion')),
                ('telemetry_trust_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_projection_runs', to='telemetry.telemetrytrustprofile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerSafeCommercialProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projection_id', models.CharField(default=apps.scheduling.models.customer_safe_commercial_projection_reference, max_length=96, unique=True)),
                ('status', models.CharField(choices=[('on_track', 'On track'), ('watch', 'Watch'), ('at_risk', 'At risk'), ('blocked', 'Blocked'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('customer_safe_eta', models.DateTimeField(blank=True, null=True)),
                ('eta_band_start', models.DateTimeField(blank=True, null=True)),
                ('eta_band_end', models.DateTimeField(blank=True, null=True)),
                ('laycan_status', models.CharField(blank=True, max_length=32)),
                ('laycan_variance_minutes', models.IntegerField(default=0)),
                ('projected_demurrage_exposure_minutes', models.PositiveIntegerField(default=0)),
                ('projected_demurrage_exposure_usd', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('commitment_risk_level', models.CharField(choices=[('low', 'Low'), ('warning', 'Warning'), ('critical', 'Critical'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('telemetry_trust_status', models.CharField(blank=True, max_length=48)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('customer_safe_to_share', models.BooleanField(default=False)),
                ('projection_only_disclaimer', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='scheduling.commercialprojectionrun')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_projections', to='scheduling.trip')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_projections', to='planning.ogvvoyage')),
            ],
            options={
                'ordering': ['voyage__laycan_start', 'voyage__voyage_id', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='commercialprojectionrun',
            index=models.Index(fields=['status', 'created_at'], name='scheduling__status_6338c5_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialprojectionrun',
            index=models.Index(fields=['plan_version', 'status', 'created_at'], name='scheduling__plan_ve_08cb08_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialprojectionrun',
            index=models.Index(fields=['telemetry_trust_profile', 'status'], name='scheduling__telemet_9dbafb_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialprojectionrun',
            index=models.Index(fields=['algorithm_version', 'status'], name='scheduling__algorit_7ca446_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialprojectionrun',
            index=models.Index(fields=['input_signature'], name='scheduling__input_s_ba4260_idx'),
        ),
        migrations.AddIndex(
            model_name='customersafecommercialprojection',
            index=models.Index(fields=['run', 'status'], name='scheduling__run_id_ba5843_idx'),
        ),
        migrations.AddIndex(
            model_name='customersafecommercialprojection',
            index=models.Index(fields=['voyage', 'run'], name='scheduling__voyage__dc3c31_idx'),
        ),
        migrations.AddIndex(
            model_name='customersafecommercialprojection',
            index=models.Index(fields=['commitment_risk_level', 'status'], name='scheduling__commitm_c98ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='customersafecommercialprojection',
            index=models.Index(fields=['customer_safe_to_share', 'status'], name='scheduling__custome_014fba_idx'),
        ),
        migrations.AddConstraint(
            model_name='customersafecommercialprojection',
            constraint=models.UniqueConstraint(fields=('run', 'voyage'), name='unique_commercial_projection_run_voyage'),
        ),
    ]
