# Generated by Django 5.2.14 on 2026-05-30 06:50

import apps.scheduling.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
        ('planning', '0002_assetavailabilitywindow_planning_as_asset_t_71225f_idx_and_more'),
        ('scheduling', '0015_commercialprojectionrun_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementAssignmentCandidateRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(default=apps.scheduling.models.movement_assignment_candidate_run_reference, max_length=96, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='queued', max_length=32)),
                ('input_signature', models.CharField(blank=True, max_length=64)),
                ('input_summary', models.JSONField(blank=True, default=dict)),
                ('algorithm_version', models.CharField(default='phase6.14-movement-assignment-candidates', max_length=96)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_movement_assignment_candidate_runs', to=settings.AUTH_USER_MODEL)),
                ('plan_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movement_assignment_candidate_runs', to='scheduling.planversion')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MovementAssignmentCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(default=apps.scheduling.models.movement_assignment_candidate_reference, max_length=96, unique=True)),
                ('movement_key', models.CharField(max_length=120)),
                ('rank', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('feasible', 'Feasible'), ('warning', 'Warning'), ('blocked', 'Blocked')], max_length=32)),
                ('score', models.DecimalField(decimal_places=3, default=0, max_digits=9)),
                ('constraint_results', models.JSONField(blank=True, default=list)),
                ('blocking_reasons', models.JSONField(blank=True, default=list)),
                ('warning_reasons', models.JSONField(blank=True, default=list)),
                ('selection_reason', models.JSONField(blank=True, default=dict)),
                ('is_selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movement_assignment_candidates', to='masters.barge')),
                ('cargo_layer_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_assignment_candidates', to='planning.cargolayerstep')),
                ('cts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movement_assignment_candidates', to='masters.ctsasset')),
                ('jetty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movement_assignment_candidates', to='masters.jetty')),
                ('route_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movement_assignment_candidates', to='masters.routesegment')),
                ('tug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movement_assignment_candidates', to='masters.tug')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='scheduling.movementassignmentcandidaterun')),
            ],
            options={
                'ordering': ['run', 'movement_key', 'rank', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='movementassignmentcandidaterun',
            index=models.Index(fields=['status', 'created_at'], name='scheduling__status_07b632_idx'),
        ),
        migrations.AddIndex(
            model_name='movementassignmentcandidaterun',
            index=models.Index(fields=['plan_version', 'status', 'created_at'], name='scheduling__plan_ve_716bea_idx'),
        ),
        migrations.AddIndex(
            model_name='movementassignmentcandidaterun',
            index=models.Index(fields=['algorithm_version', 'status'], name='scheduling__algorit_f62a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='movementassignmentcandidaterun',
            index=models.Index(fields=['input_signature'], name='scheduling__input_s_bed0bb_idx'),
        ),
        migrations.AddIndex(
            model_name='movementassignmentcandidate',
            index=models.Index(fields=['run', 'movement_key', 'rank'], name='scheduling__run_id_eb85df_idx'),
        ),
        migrations.AddIndex(
            model_name='movementassignmentcandidate',
            index=models.Index(fields=['cargo_layer_step', 'status', 'rank'], name='scheduling__cargo_l_a34f14_idx'),
        ),
        migrations.AddIndex(
            model_name='movementassignmentcandidate',
            index=models.Index(fields=['status', 'score'], name='scheduling__status_a760fe_idx'),
        ),
        migrations.AddIndex(
            model_name='movementassignmentcandidate',
            index=models.Index(fields=['is_selected', 'run'], name='scheduling__is_sele_78a6e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='movementassignmentcandidate',
            constraint=models.UniqueConstraint(fields=('run', 'cargo_layer_step', 'rank'), name='unique_movement_assignment_candidate_rank'),
        ),
    ]
