# Generated by Django 5.2.14 on 2026-05-15 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAvailabilityWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('tug', 'Tug'), ('barge', 'Barge'), ('cts', 'CTS')], max_length=20)),
                ('asset_code', models.CharField(max_length=80)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('maintenance', 'Maintenance'), ('breakdown', 'Breakdown')], max_length=32)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['window_start', 'asset_type', 'asset_code'],
            },
        ),
        migrations.CreateModel(
            name='BridgeWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('clearance_m', models.DecimalField(decimal_places=2, max_digits=5)),
                ('allowed_asset_class', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('open', 'Open'), ('restricted', 'Restricted'), ('closed', 'Closed')], default='open', max_length=32)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bridge_windows', to='masters.location')),
            ],
            options={
                'ordering': ['window_start', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('ogv_demand', 'OGV demand'), ('calendar', 'Calendar'), ('layer_sequence', 'Layer sequence')], max_length=40)),
                ('filename', models.CharField(blank=True, max_length=180)),
                ('source', models.CharField(default='manual', max_length=120)),
                ('status', models.CharField(choices=[('validated', 'Validated'), ('failed', 'Failed'), ('imported', 'Imported')], default='validated', max_length=32)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JettyAvailabilityWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('working', 'Working'), ('blocked', 'Blocked'), ('reduced', 'Reduced'), ('maintenance', 'Maintenance')], max_length=32)),
                ('loading_rate_override_tph', models.PositiveIntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jetty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_windows', to='masters.jetty')),
            ],
            options={
                'ordering': ['window_start', 'jetty__code'],
            },
        ),
        migrations.CreateModel(
            name='OGVVoyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voyage_id', models.CharField(max_length=80, unique=True)),
                ('vessel_name', models.CharField(max_length=160)),
                ('customer_name', models.CharField(max_length=160)),
                ('vessel_class', models.CharField(blank=True, max_length=80)),
                ('eta', models.DateTimeField()),
                ('etb', models.DateTimeField(blank=True, null=True)),
                ('etc_target', models.DateTimeField(blank=True, null=True)),
                ('laycan_start', models.DateTimeField()),
                ('laycan_end', models.DateTimeField()),
                ('required_mt', models.PositiveIntegerField()),
                ('loaded_mt', models.PositiveIntegerField(default=0)),
                ('in_transit_mt', models.PositiveIntegerField(default=0)),
                ('discharged_mt', models.PositiveIntegerField(default=0)),
                ('priority', models.PositiveIntegerField(default=3)),
                ('demurrage_rate_usd_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('at_risk', 'At risk'), ('completed', 'Completed'), ('hold', 'Hold')], default='planned', max_length=32)),
                ('risk_status', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('demurrage', 'Demurrage')], default='low', max_length=32)),
                ('current_stage', models.CharField(blank=True, max_length=80)),
                ('next_blocking_constraint', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anchorage_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ogv_voyages', to='masters.location')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ogv_voyages', to='organizations.organization')),
            ],
            options={
                'ordering': ['laycan_start', 'priority', 'vessel_name'],
            },
        ),
        migrations.CreateModel(
            name='NavigationConstraintCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(max_length=80)),
                ('constraint_type', models.CharField(choices=[('tide', 'Tide'), ('bridge', 'Bridge')], max_length=20)),
                ('eta_gate', models.DateTimeField()),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('draft_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('margin_minutes', models.IntegerField()),
                ('status', models.CharField(choices=[('can_cross', 'Can cross'), ('waiting', 'Waiting'), ('marginal', 'Marginal'), ('missed', 'Missed')], max_length=32)),
                ('recovery_hint', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='constraint_checks', to='masters.routesegment')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraint_checks', to='planning.ogvvoyage')),
            ],
            options={
                'ordering': ['eta_gate', 'voyage__voyage_id'],
            },
        ),
        migrations.CreateModel(
            name='CargoRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_mt', models.PositiveIntegerField()),
                ('loaded_mt', models.PositiveIntegerField(default=0)),
                ('in_transit_mt', models.PositiveIntegerField(default=0)),
                ('discharged_mt', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('loading', 'Loading'), ('partial', 'Partial'), ('complete', 'Complete'), ('hold', 'Hold')], default='planned', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coal_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargo_requirements', to='masters.coalgrade')),
                ('preferred_jetty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargo_requirements', to='masters.jetty')),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargo_requirements', to='masters.location')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='planning.ogvvoyage')),
            ],
            options={
                'ordering': ['voyage__laycan_start', 'coal_grade__sequence_priority'],
            },
        ),
        migrations.CreateModel(
            name='CargoLayerStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hatch_no', models.PositiveIntegerField()),
                ('layer_no', models.PositiveIntegerField()),
                ('required_sequence_no', models.PositiveIntegerField()),
                ('required_mt', models.PositiveIntegerField()),
                ('remaining_mt', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('queued', 'Queued'), ('loading', 'Loading'), ('completed', 'Completed'), ('blocked', 'Blocked'), ('qc_hold', 'QC hold')], default='planned', max_length=32)),
                ('blocking_reason', models.CharField(blank=True, max_length=255)),
                ('chain_status', models.CharField(blank=True, max_length=80)),
                ('sequence_violation', models.BooleanField(default=False)),
                ('planned_start', models.DateTimeField(blank=True, null=True)),
                ('planned_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coal_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargo_layer_steps', to='masters.coalgrade')),
                ('planned_barge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planned_layer_steps', to='masters.barge')),
                ('planned_cts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planned_layer_steps', to='masters.ctsasset')),
                ('planned_jetty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planned_layer_steps', to='masters.jetty')),
                ('cargo_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layer_steps', to='planning.cargorequirement')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_steps', to='planning.ogvvoyage')),
            ],
            options={
                'ordering': ['voyage__laycan_start', 'voyage__voyage_id', 'required_sequence_no'],
            },
        ),
        migrations.CreateModel(
            name='TideWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('min_water_level_m', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_loaded_draft_m', models.DecimalField(decimal_places=2, max_digits=5)),
                ('risk_level', models.CharField(choices=[('normal', 'Normal'), ('tight', 'Tight'), ('closed', 'Closed')], default='normal', max_length=32)),
                ('source', models.CharField(default='manual', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_route_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tide_windows', to='masters.routesegment')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tide_windows', to='masters.location')),
            ],
            options={
                'ordering': ['window_start', 'code'],
            },
        ),
        migrations.AddIndex(
            model_name='ogvvoyage',
            index=models.Index(fields=['status', 'risk_status'], name='planning_og_status_7ab6ed_idx'),
        ),
        migrations.AddIndex(
            model_name='ogvvoyage',
            index=models.Index(fields=['laycan_start', 'laycan_end'], name='planning_og_laycan__5b7a87_idx'),
        ),
        migrations.AddIndex(
            model_name='navigationconstraintcheck',
            index=models.Index(fields=['constraint_type', 'status'], name='planning_na_constra_f57ed2_idx'),
        ),
        migrations.AddConstraint(
            model_name='cargolayerstep',
            constraint=models.UniqueConstraint(fields=('voyage', 'required_sequence_no'), name='unique_voyage_layer_sequence'),
        ),
    ]
