# Generated by Django 5.2.14 on 2026-05-16 02:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assetavailabilitywindow',
            index=models.Index(fields=['asset_type', 'asset_code', 'window_start', 'window_end'], name='planning_as_asset_t_71225f_idx'),
        ),
        migrations.AddIndex(
            model_name='assetavailabilitywindow',
            index=models.Index(fields=['status', 'window_start'], name='planning_as_status_ef8f61_idx'),
        ),
        migrations.AddIndex(
            model_name='bridgewindow',
            index=models.Index(fields=['location', 'window_start', 'window_end'], name='planning_br_locatio_b87138_idx'),
        ),
        migrations.AddIndex(
            model_name='bridgewindow',
            index=models.Index(fields=['is_active', 'status', 'window_start'], name='planning_br_is_acti_e48fbc_idx'),
        ),
        migrations.AddIndex(
            model_name='cargolayerstep',
            index=models.Index(fields=['voyage', 'status', 'required_sequence_no'], name='planning_ca_voyage__1b5b44_idx'),
        ),
        migrations.AddIndex(
            model_name='cargolayerstep',
            index=models.Index(fields=['planned_start', 'planned_end'], name='planning_ca_planned_b5636e_idx'),
        ),
        migrations.AddIndex(
            model_name='cargolayerstep',
            index=models.Index(fields=['sequence_violation', 'status'], name='planning_ca_sequenc_41e4a7_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['import_type', 'status', 'created_at'], name='planning_im_import__3e3ff8_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['created_by', 'created_at'], name='planning_im_created_3b134d_idx'),
        ),
        migrations.AddIndex(
            model_name='jettyavailabilitywindow',
            index=models.Index(fields=['jetty', 'window_start', 'window_end'], name='planning_je_jetty_i_10aaf3_idx'),
        ),
        migrations.AddIndex(
            model_name='jettyavailabilitywindow',
            index=models.Index(fields=['status', 'window_start'], name='planning_je_status_225d7c_idx'),
        ),
        migrations.AddIndex(
            model_name='navigationconstraintcheck',
            index=models.Index(fields=['voyage', 'constraint_type', 'status'], name='planning_na_voyage__131305_idx'),
        ),
        migrations.AddIndex(
            model_name='navigationconstraintcheck',
            index=models.Index(fields=['asset_code', 'eta_gate'], name='planning_na_asset_c_4c1623_idx'),
        ),
        migrations.AddIndex(
            model_name='tidewindow',
            index=models.Index(fields=['location', 'window_start', 'window_end'], name='planning_ti_locatio_c6425f_idx'),
        ),
        migrations.AddIndex(
            model_name='tidewindow',
            index=models.Index(fields=['is_active', 'risk_level', 'window_start'], name='planning_ti_is_acti_488efc_idx'),
        ),
    ]
